# Generated by Django 6.0.4 on 2026-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
