# Generated by Django 6.0.6 on 2026-06-15 14:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('zona', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('hectareas', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('variedad', models.CharField(choices=[('Duke', 'Duke'), ('Legacy', 'Legacy'), ('Brigitta', 'Brigitta'), ('Liberty', 'Liberty')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuarteles', to='cosecha.supervisor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='cosecha.supervisor')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('horas', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(12)])),
                ('calidad', models.CharField(choices=[('Exportacion', 'Exportacion'), ('Nacional', 'Nacional'), ('Descarte', 'Descarte')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuartel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='cosecha.cuartel')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='cosecha.trabajador')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('objeto_id', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('datos_previos', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['accion'], name='cosecha_aud_accion_0f2410_idx'), models.Index(fields=['modelo'], name='cosecha_aud_modelo_5e6a7a_idx'), models.Index(fields=['timestamp'], name='cosecha_aud_timesta_fe58e6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['rut'], name='cosecha_sup_rut_33cdc3_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['activo'], name='cosecha_sup_activo_eebc04_idx'),
        ),
        migrations.AddIndex(
            model_name='cuartel',
            index=models.Index(fields=['nombre'], name='cosecha_cua_nombre_3d85cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cuartel',
            index=models.Index(fields=['activo'], name='cosecha_cua_activo_9a184c_idx'),
        ),
        migrations.AddIndex(
            model_name='cuartel',
            index=models.Index(fields=['supervisor'], name='cosecha_cua_supervi_e4d261_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['rut'], name='cosecha_tra_rut_739780_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['activo'], name='cosecha_tra_activo_754f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['supervisor'], name='cosecha_tra_supervi_3e47a5_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['fecha'], name='cosecha_reg_fecha_8f4456_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['calidad'], name='cosecha_reg_calidad_e3f9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['trabajador'], name='cosecha_reg_trabaja_3f2dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['cuartel'], name='cosecha_reg_cuartel_2925f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='registrocosecha',
            constraint=models.UniqueConstraint(fields=('trabajador', 'cuartel', 'fecha'), name='unique_registro_trabajador_cuartel_fecha'),
        ),
    ]
