# Generated by Django 6.0.4 on 2026-06-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_cliente_usuario_mecanico_usuario_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
