# Generated by Django 6.0.4 on 2026-06-03 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_ordentrabajo_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=200)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo_origen', models.CharField(max_length=255)),
                ('fila_excel', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='servicio.ordentrabajo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('archivo_origen', 'fila_excel'), name='unique_repuesto_archivo_fila')],
            },
        ),
    ]
