# Generated by Django 6.0.4 on 2026-04-27 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporeros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('hectareas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('variedad', models.CharField(choices=[('Duke', 'Duke'), ('Legacy', 'Legacy'), ('Brigitta', 'Brigitta'), ('Star', 'Star')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Poda', 'Poda'), ('Cosecha', 'Cosecha'), ('Riego', 'Riego'), ('Pesticida', 'Pesticida'), ('Limpieza', 'Limpieza')], max_length=30)),
                ('fecha', models.DateField()),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('kilos_cosechados', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cuartel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labores', to='temporeros.cuartel')),
                ('temporero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labores', to='temporeros.temporero')),
            ],
            options={
                'ordering': ['-fecha', 'temporero__nombre'],
                'constraints': [models.UniqueConstraint(fields=('temporero', 'cuartel', 'tipo', 'fecha'), name='unique_labor_por_dia')],
            },
        ),
    ]
