### 1. Lista todos los temporeros = HTTP/1.1 200 OK
GET http://127.0.0.1:8000/api/temporeros/
Content-Type: application/json

###

### 2. Solo supervisores activos = HTTP/1.1 200 OK
GET http://127.0.0.1:8000/api/temporeros/?activo=true&supervisor=true
Content-Type: application/json

###

### 3. Buscar por nombre = HTTP/1.1 200 OK
GET http://127.0.0.1:8000/api/temporeros/?buscar=juan
Content-Type: application/json

###

### 4. Detalle temporero existente = HTTP/1.1 200 OK
GET http://127.0.0.1:8000/api/temporeros/44444444-4/
Content-Type: application/json

###

### 5. Detalle temporero inexistente = HTTP/1.1 404 Not Found
GET http://127.0.0.1:8000/api/temporeros/99999999-9/
Content-Type: application/json

###

### 6. Cuarteles variedad Legacy = HTTP/1.1 200 OK
GET http://127.0.0.1:8000/api/cuarteles/?variedad=Legacy
Content-Type: application/json

###

### 7. Detalle cuartel A-1 = HTTP/1.1 200 OK
GET http://127.0.0.1:8000/api/cuarteles/A-1/
Content-Type: application/json

###

### 8. Labores Cosecha en rango de fechas = HTTP/1.1 200 OK
GET http://127.0.0.1:8000/api/labores/?tipo=Cosecha&desde=2026-03-30&hasta=2026-05-06
Content-Type: application/json

###

### 9. Resumen general = HTTP/1.1 200 OK
GET http://127.0.0.1:8000/api/resumen/
Content-Type: application/json

###

### 10. Crear labor válida = HTTP/1.1 201 Created D
POST http://127.0.0.1:8000/api/labores/
Content-Type: application/json

{
    "temporero": 12,
    "cuartel": 69,
    "tipo": "Riego",
    "fecha": "2026-05-06",
    "horas_trabajadas": 8.0,
    "kilos_cosechados": null,
    "observaciones": "Prueba REST Client"
}

###

### 11. Cosecha sin kilos = HTTP/1.1 400 Bad Request
POST http://127.0.0.1:8000/api/labores/
Content-Type: application/json

{
    "temporero": 12,
    "cuartel": 69,
    "tipo": "Cosecha",
    "fecha": "2026-05-09",
    "horas_trabajadas": 8.0,
    "observaciones": "Debe fallar"
}

###

### 12. Método no permitido = HTTP/1.1 405 Method Not Allowed
POST http://127.0.0.1:8000/api/temporeros/
Content-Type: application/json

{}