import os
import sys
import django

sys.path.append(os.path.join(os.path.dirname(__file__), 'proyecto_django'))

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'campo.settings')
django.setup()

from temporeros.models import Temporero

#Evidencia sqlmigrate
#(venv) chris@zChriuz:~/practica-terrasoft-2026/23-04-2026/proyecto_django$ python3 manage.py sqlmigrate temporeros 0001
#BEGIN;
#--
#-- Create model Temporero
#--
#CREATE TABLE "temporeros_temporero" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(100) NOT NULL, "rut" varchar(12) NOT NULL UNIQUE, "telefono" varchar(20) NULL, "contacto_emergencia" varchar(100) NULL, "fecha_ingreso" date NOT NULL, "supervisor" boolean NOT NULL, "fecha_nacimiento" date NOT NULL, "talla_polera" varchar(2) NOT NULL, "activo" boolean NOT NULL);
#CREATE INDEX "temporeros_temporero_rut_efec4fe4_like" ON "temporeros_temporero" ("rut" varchar_pattern_ops);
#COMMIT;


#temporada_django=> \dt
#                 List of relations
#Schema |            Name            | Type  | Owner
#-------+----------------------------+-------+-------
#public | auth_group                 | table | admin
#public | auth_group_permissions     | table | admin
#public | auth_permission            | table | admin
#public | auth_user                  | table | admin
#public | auth_user_groups           | table | admin
#public | auth_user_user_permissions | table | admin
#public | django_admin_log           | table | admin
#public | django_content_type        | table | admin
#public | django_migrations          | table | admin
#public | django_session             | table | admin
#public | temporeros_temporero       | table | admin

#temporada_django=> \d
#                      List of relations
#Schema |               Name                |   Type   | Owner
#-------+-----------------------------------+----------+-------
#public | auth_group                        | table    | admin
#public | auth_group_id_seq                 | sequence | admin
#public | auth_group_permissions            | table    | admin
#public | auth_group_permissions_id_seq     | sequence | admin
#public | auth_permission                   | table    | admin
#public | auth_permission_id_seq            | sequence | admin
#public | auth_user                         | table    | admin
#public | auth_user_groups                  | table    | admin
#public | auth_user_groups_id_seq           | sequence | admin
#public | auth_user_id_seq                  | sequence | admin
#public | auth_user_user_permissions        | table    | admin
#public | auth_user_user_permissions_id_seq | sequence | admin
#public | django_admin_log                  | table    | admin
#public | django_admin_log_id_seq           | sequence | admin
#public | django_content_type               | table    | admin
#public | django_content_type_id_seq        | sequence | admin
#public | django_migrations                 | table    | admin
#public | django_migrations_id_seq          | sequence | admin
#public | django_session                    | table    | admin
#public | temporeros_temporero              | table    | admin
#public | temporeros_temporero_id_seq       | sequence | admin



# ================================
# CONSULTAS ORM - TEMPOREROS
# ================================

from temporeros.models import Temporero
from django.db.models import Q, Count, Avg, F, ExpressionWrapper, IntegerField, Case, When, Value, CharField
from django.db.models.functions import Now, ExtractYear


#1- Listar temporeros activos ordenados por fecha de ingreso (más nuevo primero)
temporeros = Temporero.objects.filter(activo=True).order_by('-fecha_ingreso')

print("\n--- Temporeros activos ordenados ---")
for t in temporeros:
    print(t.nombre, t.fecha_ingreso)


#2- Buscar temporero por RUT con manejo de error
print("\n--- Buscar temporero por RUT ---")
try:
    t = Temporero.objects.get(rut="11111111-1")
    print(t.nombre, t.rut)
except Temporero.DoesNotExist:
    print("Temporero no encontrado")


#3- Contar supervisores activos
print("\n--- Supervisores activos ---")
cantidad = Temporero.objects.filter(supervisor=True, activo=True).count()
print("Cantidad:", cantidad)


#4- Marcar un temporero como inactivo
print("\n--- Marcar temporero como inactivo ---")
Temporero.objects.filter(rut="11111111-1").update(activo=False)

t = Temporero.objects.get(rut="11111111-1")
print(t.nombre, t.activo)


#5- Nombres que empiezan con J o M
print("\n--- Nombres con J o M ---")
for t in Temporero.objects.filter(
    Q(nombre__istartswith='j') | Q(nombre__istartswith='m')
):
    print(t.nombre)


#6- Cantidad por talla de polera
print("\n--- Cantidad por talla ---")
for t in Temporero.objects.values('talla_polera').annotate(total=Count('id')).order_by('-total'):
    print(t['talla_polera'], t['total'])


#7- Promedio de edad (supervisores vs no supervisores)
edad = ExpressionWrapper(
    ExtractYear(Now()) - ExtractYear(F('fecha_nacimiento')),
    output_field=IntegerField()
)

print("\n--- Promedio de edad ---")
sup = Temporero.objects.filter(supervisor=True).aggregate(promedio=Avg(edad))
no_sup = Temporero.objects.filter(supervisor=False).aggregate(promedio=Avg(edad))

print("Supervisores:", sup)
print("No supervisores:", no_sup)


#8- Agrupación por rangos de edad
print("\n--- Rangos de edad ---")

rangos = Temporero.objects.filter(activo=True).annotate(
    edad_calculada=edad
).annotate(
    rango=Case(
        When(edad_calculada__lt=30, then=Value("Menores de 30")),
        When(edad_calculada__gte=30, edad_calculada__lte=50, then=Value("Entre 30 y 50")),
        When(edad_calculada__gt=50, then=Value("Mayores de 50")),
        output_field=CharField()
    )
).values('rango').annotate(total=Count('id')).order_by('rango')

for r in rangos:
    print(r['rango'], r['total'])

from datetime import date

Temporero.objects.all().delete()

temporeros = [
    Temporero(nombre="Ana Diaz", rut="44444444-4", telefono=None, contacto_emergencia="Luis Diaz", fecha_ingreso=date(2024, 3, 1), supervisor=True, fecha_nacimiento=date(1985, 2, 10), talla_polera="XL", activo=False),
    Temporero(nombre="Andres Pino", rut="46464646-6", telefono=None, contacto_emergencia="Rosa Pino", fecha_ingreso=date(2024, 4, 12), supervisor=True, fecha_nacimiento=date(1980, 3, 22), talla_polera="M", activo=True),
    Temporero(nombre="Camila Fuentes", rut="51515151-1", telefono="955667788", contacto_emergencia="Maria Fuentes", fecha_ingreso=date(2024, 4, 12), supervisor=True, fecha_nacimiento=date(1997, 2, 17), talla_polera="L", activo=True),
    Temporero(nombre="Chris C", rut="21212121-1", telefono="999999999", contacto_emergencia="Carlos C", fecha_ingreso=date(2024, 4, 5), supervisor=False, fecha_nacimiento=date(1999, 6, 15), talla_polera="M", activo=False),
    Temporero(nombre="Daniela Castro", rut="47474747-7", telefono="922334455", contacto_emergencia="Pedro Castro", fecha_ingreso=date(2024, 4, 10), supervisor=False, fecha_nacimiento=date(2006, 1, 10), talla_polera="L", activo=True),
    Temporero(nombre="Diego Salas", rut="57575757-7", telefono="988990011", contacto_emergencia="Laura Salas", fecha_ingreso=date(2024, 4, 9), supervisor=False, fecha_nacimiento=date(2005, 4, 4), talla_polera="XL", activo=True),
    Temporero(nombre="Felipe Rojas", rut="48484848-8", telefono="933445566", contacto_emergencia="Marta Rojas", fecha_ingreso=date(2024, 3, 30), supervisor=False, fecha_nacimiento=date(1975, 9, 9), talla_polera="XL", activo=True),
    Temporero(nombre="Fernanda Soto", rut="53535353-3", telefono="966778899", contacto_emergencia="Carlos Soto", fecha_ingreso=date(2024, 4, 20), supervisor=False, fecha_nacimiento=date(2003, 12, 1), talla_polera="S", activo=True),
    Temporero(nombre="Jorge Herrera", rut="50505050-0", telefono="944556677", contacto_emergencia="Ana Herrera", fecha_ingreso=date(2024, 4, 5), supervisor=False, fecha_nacimiento=date(1960, 5, 5), talla_polera="M", activo=True),
    Temporero(nombre="Laura Mendez", rut="45454545-5", telefono="911223344", contacto_emergencia="Carlos Mendez", fecha_ingreso=date(2024, 4, 8), supervisor=False, fecha_nacimiento=date(1992, 7, 14), talla_polera="S", activo=True),
    Temporero(nombre="Luis Navarro", rut="54545454-4", telefono="977889900", contacto_emergencia="Elena Navarro", fecha_ingreso=date(2024, 3, 28), supervisor=True, fecha_nacimiento=date(1972, 8, 8), talla_polera="M", activo=True),
    Temporero(nombre="Maria Soto", rut="11111111-1", telefono=None, contacto_emergencia="Carlos Soto", fecha_ingreso=date(2024, 4, 10), supervisor=False, fecha_nacimiento=date(2005, 3, 15), talla_polera="S", activo=False),
    Temporero(nombre="Patricia Rios", rut="56565656-6", telefono=None, contacto_emergencia="Juan Rios", fecha_ingreso=date(2024, 4, 7), supervisor=False, fecha_nacimiento=date(1994, 10, 21), talla_polera="L", activo=True),
    Temporero(nombre="Rodrigo Vega", rut="52525252-2", telefono=None, contacto_emergencia="Pedro Vega", fecha_ingreso=date(2024, 4, 1), supervisor=False, fecha_nacimiento=date(1988, 6, 30), talla_polera="XL", activo=True),
    Temporero(nombre="Valeria Torres", rut="58585858-8", telefono="999001122", contacto_emergencia="Miguel Torres", fecha_ingreso=date(2024, 4, 11), supervisor=True, fecha_nacimiento=date(1991, 3, 3), talla_polera="S", activo=True),
]

Temporero.objects.bulk_create(temporeros)

print("Temporeros creados correctamente")
